name: publish package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # 发布到github package
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@shuli495'
    - run: npm install
    - run: tsc
    - run: cd lib & ls
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
